kind: pipeline
name: default

steps:
- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.52
    pull: always
    url: https://cbrgmtest.net
    validate: true

# - name: deploy
#   image: appleboy/drone-scp
#   settings:
#     host: cbrgm.net
#     target: /var/www/site
#     source: public/*
#     username:
#       from_secret: ssh_username
#     password:
#       from_secret: ssh_password
#     port:
#       from_secret: ssh_port
#   when:
#     branch:
#     - master
#     event:
#       exclude:
#       - pull_request
